let arr = [
    {
        "gantt_data_id": 21334,
        "location_id": 336,
        "location_name": "Allcargo Building",
        "sub_loc_id": 1814,
        "sub_loc_name": "3rd Floor",
        "sub_location_id": 4209,
        "sub_sub_loc_name": "A Wing",
        "linking_activity_id": 52293,
        "activity_head": "Painting",
        "activity": "Ceiling",
        "productivity": 10,
        "quantity": 100,
        "id": "",
        "to_link": 52272,
        "relation": "FS",
        "buffer": -5
    },
    {
        "gantt_data_id": 21335,
        "location_id": 336,
        "location_name": "Allcargo Building",
        "sub_loc_id": 1814,
        "sub_loc_name": "3rd Floor",
        "sub_location_id": 4209,
        "sub_sub_loc_name": "A Wing",
        "linking_activity_id": 52280,
        "activity_head": "Panelling",
        "activity": "Mirror",
        "productivity": 3.8,
        "quantity": 100,
        "id": "",
        "to_link": 52270,
        "relation": "FS",
        "buffer": -15
    },
    {
        "gantt_data_id": 21336,
        "location_id": 336,
        "location_name": "Allcargo Building",
        "sub_loc_id": 1814,
        "sub_loc_name": "3rd Floor",
        "sub_location_id": 4209,
        "sub_sub_loc_name": "A Wing",
        "linking_activity_id": 52281,
        "activity_head": "Panelling",
        "activity": "Accoustic",
        "productivity": 3.8,
        "quantity": 100,
        "id": "",
        "to_link": 52270,
        "relation": "FS",
        "buffer": -15
    },
    {
        "gantt_data_id": 21337,
        "location_id": 336,
        "location_name": "Allcargo Building",
        "sub_loc_id": 1814,
        "sub_loc_name": "3rd Floor",
        "sub_location_id": 4209,
        "sub_sub_loc_name": "A Wing",
        "linking_activity_id": 52282,
        "activity_head": "Partition",
        "activity": "Sliding Glass",
        "productivity": 3.8,
        "quantity": 100,
        "id": "",
        "to_link": 52270,
        "relation": "FS",
        "buffer": -15
    },
    {
        "gantt_data_id": 21338,
        "location_id": 336,
        "location_name": "Allcargo Building",
        "sub_loc_id": 1814,
        "sub_loc_name": "3rd Floor",
        "sub_location_id": 4209,
        "sub_sub_loc_name": "A Wing",
        "linking_activity_id": 52283,
        "activity_head": "Aluminium",
        "activity": "Screen",
        "productivity": 3.8,
        "quantity": 100,
        "id": "",
        "to_link": 52270,
        "relation": "FS",
        "buffer": -15
    },
    {
        "gantt_data_id": 21339,
        "location_id": 336,
        "location_name": "Allcargo Building",
        "sub_loc_id": 1814,
        "sub_loc_name": "3rd Floor",
        "sub_location_id": 4209,
        "sub_sub_loc_name": "A Wing",
        "linking_activity_id": 52284,
        "activity_head": "Laminate",
        "activity": "Cladding",
        "productivity": 3.8,
        "quantity": 100,
        "id": "",
        "to_link": 52270,
        "relation": "FS",
        "buffer": -15
    },
    {
        "gantt_data_id": 21340,
        "location_id": 336,
        "location_name": "Allcargo Building",
        "sub_loc_id": 1814,
        "sub_loc_name": "3rd Floor",
        "sub_location_id": 4209,
        "sub_sub_loc_name": "A Wing",
        "linking_activity_id": 52285,
        "activity_head": "Metal Edge",
        "activity": "Profile",
        "productivity": 3.8,
        "quantity": 100,
        "id": "",
        "to_link": 52270,
        "relation": "FS",
        "buffer": -15
    },
    {
        "gantt_data_id": 21341,
        "location_id": 336,
        "location_name": "Allcargo Building",
        "sub_loc_id": 1814,
        "sub_loc_name": "3rd Floor",
        "sub_location_id": 4209,
        "sub_sub_loc_name": "A Wing",
        "linking_activity_id": 52286,
        "activity_head": "Carpet",
        "activity": "Flooring",
        "productivity": 3.8,
        "quantity": 100,
        "id": "",
        "to_link": 52270,
        "relation": "FS",
        "buffer": -15
    },
    {
        "gantt_data_id": 21342,
        "location_id": 336,
        "location_name": "Allcargo Building",
        "sub_loc_id": 1814,
        "sub_loc_name": "3rd Floor",
        "sub_location_id": 4209,
        "sub_sub_loc_name": "A Wing",
        "linking_activity_id": 52287,
        "activity_head": "Deck",
        "activity": "Edging",
        "productivity": 3.8,
        "quantity": 100,
        "id": "",
        "to_link": 52270,
        "relation": "FS",
        "buffer": -15
    },
    {
        "gantt_data_id": 21343,
        "location_id": 336,
        "location_name": "Allcargo Building",
        "sub_loc_id": 1814,
        "sub_loc_name": "3rd Floor",
        "sub_location_id": 4209,
        "sub_sub_loc_name": "A Wing",
        "linking_activity_id": 52288,
        "activity_head": "Glass",
        "activity": "Black Painted",
        "productivity": 3.8,
        "quantity": 100,
        "id": "",
        "to_link": 52270,
        "relation": "FS",
        "buffer": -15
    },
    {
        "gantt_data_id": 21344,
        "location_id": 336,
        "location_name": "Allcargo Building",
        "sub_loc_id": 1814,
        "sub_loc_name": "3rd Floor",
        "sub_location_id": 4209,
        "sub_sub_loc_name": "A Wing",
        "linking_activity_id": 52289,
        "activity_head": "Furniture",
        "activity": "Modular",
        "productivity": 14.3,
        "quantity": 100,
        "id": "",
        "relation": "PS",
        "buffer": 50
    },
    {
        "gantt_data_id": 21345,
        "location_id": 336,
        "location_name": "Allcargo Building",
        "sub_loc_id": 1814,
        "sub_loc_name": "3rd Floor",
        "sub_location_id": 4209,
        "sub_sub_loc_name": "A Wing",
        "linking_activity_id": 52290,
        "activity_head": "Furniture",
        "activity": "Loose",
        "productivity": 50,
        "quantity": 100,
        "id": "",
        "relation": "PS",
        "buffer": 55
    },
    {
        "gantt_data_id": 21346,
        "location_id": 336,
        "location_name": "Allcargo Building",
        "sub_loc_id": 1814,
        "sub_loc_name": "3rd Floor",
        "sub_location_id": 4209,
        "sub_sub_loc_name": "A Wing",
        "linking_activity_id": 52291,
        "activity_head": "Plumbing and Sanitary",
        "activity": "Toilet",
        "productivity": 10,
        "quantity": 100,
        "id": "",
        "to_link": 52261,
        "relation": "FS",
        "buffer": -5
    },
    {
        "gantt_data_id": 21347,
        "location_id": 336,
        "location_name": "Allcargo Building",
        "sub_loc_id": 1814,
        "sub_loc_name": "3rd Floor",
        "sub_location_id": 4209,
        "sub_sub_loc_name": "A Wing",
        "linking_activity_id": 52292,
        "activity_head": "Plumbing and Sanitary",
        "activity": "Pantry",
        "productivity": 10,
        "quantity": 100,
        "id": "",
        "to_link": 52261,
        "relation": "FS",
        "buffer": -5
    },
    {
        "gantt_data_id": 21348,
        "location_id": 336,
        "location_name": "Allcargo Building",
        "sub_loc_id": 1814,
        "sub_loc_name": "3rd Floor",
        "sub_location_id": 4209,
        "sub_sub_loc_name": "A Wing",
        "linking_activity_id": 52279,
        "activity_head": "Panelling",
        "activity": "MDF",
        "productivity": 3.8,
        "quantity": 100,
        "id": "",
        "to_link": 52270,
        "relation": "FS",
        "buffer": -15
    },
    {
        "gantt_data_id": 21349,
        "location_id": 336,
        "location_name": "Allcargo Building",
        "sub_loc_id": 1814,
        "sub_loc_name": "3rd Floor",
        "sub_location_id": 4209,
        "sub_sub_loc_name": "A Wing",
        "linking_activity_id": 52294,
        "activity_head": "Painting",
        "activity": "Walls",
        "productivity": 10,
        "quantity": 100,
        "id": "",
        "to_link": 52293,
        "relation": "SS",
        "buffer": 0
    },
    {
        "gantt_data_id": 21350,
        "location_id": 336,
        "location_name": "Allcargo Building",
        "sub_loc_id": 1814,
        "sub_loc_name": "3rd Floor",
        "sub_location_id": 4209,
        "sub_sub_loc_name": "A Wing",
        "linking_activity_id": 52295,
        "activity_head": "Electrical & Networking",
        "activity": "Work",
        "productivity": 4.3,
        "quantity": 100,
        "id": "",
        "to_link": 52272,
        "relation": "SF",
        "buffer": -2
    },
    {
        "gantt_data_id": 21351,
        "location_id": 336,
        "location_name": "Allcargo Building",
        "sub_loc_id": 1814,
        "sub_loc_name": "3rd Floor",
        "sub_location_id": 4209,
        "sub_sub_loc_name": "A Wing",
        "linking_activity_id": 52296,
        "activity_head": "Systems",
        "activity": "Public Address",
        "productivity": 4,
        "quantity": 100,
        "id": "",
        "to_link": 52270,
        "relation": "FS",
        "buffer": -15
    },
    {
        "gantt_data_id": 21352,
        "location_id": 336,
        "location_name": "Allcargo Building",
        "sub_loc_id": 1814,
        "sub_loc_name": "3rd Floor",
        "sub_location_id": 4209,
        "sub_sub_loc_name": "A Wing",
        "linking_activity_id": 52297,
        "activity_head": "Systems",
        "activity": "Fire Alarn",
        "productivity": 4,
        "quantity": 100,
        "id": "",
        "to_link": 52270,
        "relation": "FS",
        "buffer": -15
    },
    {
        "gantt_data_id": 21353,
        "location_id": 336,
        "location_name": "Allcargo Building",
        "sub_loc_id": 1814,
        "sub_loc_name": "3rd Floor",
        "sub_location_id": 4209,
        "sub_sub_loc_name": "A Wing",
        "linking_activity_id": 52298,
        "activity_head": "Systems",
        "activity": "Sprinkler",
        "productivity": 4,
        "quantity": 100,
        "id": "",
        "to_link": 52270,
        "relation": "FS",
        "buffer": -15
    },
    {
        "gantt_data_id": 21354,
        "location_id": 336,
        "location_name": "Allcargo Building",
        "sub_loc_id": 1814,
        "sub_loc_name": "3rd Floor",
        "sub_location_id": 4209,
        "sub_sub_loc_name": "A Wing",
        "linking_activity_id": 52299,
        "activity_head": "Systems",
        "activity": "Access Control",
        "productivity": 4,
        "quantity": 100,
        "id": "",
        "to_link": 52270,
        "relation": "FS",
        "buffer": -15
    },
    {
        "gantt_data_id": 21355,
        "location_id": 336,
        "location_name": "Allcargo Building",
        "sub_loc_id": 1814,
        "sub_loc_name": "3rd Floor",
        "sub_location_id": 4209,
        "sub_sub_loc_name": "A Wing",
        "linking_activity_id": 52300,
        "activity_head": "Misc",
        "activity": "House Keeping",
        "productivity": 14.3,
        "quantity": 100,
        "id": "",
        "to_link": 52289,
        "relation": "FS",
        "buffer": 0
    },
    {
        "gantt_data_id": 21356,
        "location_id": 336,
        "location_name": "Allcargo Building",
        "sub_loc_id": 1814,
        "sub_loc_name": "3rd Floor",
        "sub_location_id": 4209,
        "sub_sub_loc_name": "A Wing",
        "linking_activity_id": 52301,
        "activity_head": "Misc",
        "activity": "Frosted Film",
        "productivity": 14.3,
        "quantity": 100,
        "id": "",
        "to_link": 52289,
        "relation": "FS",
        "buffer": 0
    },
    {
        "gantt_data_id": 21357,
        "location_id": 336,
        "location_name": "Allcargo Building",
        "sub_loc_id": 1814,
        "sub_loc_name": "3rd Floor",
        "sub_location_id": 4209,
        "sub_sub_loc_name": "A Wing",
        "linking_activity_id": 52302,
        "activity_head": "Misc",
        "activity": "Roller Blinds",
        "productivity": 14.3,
        "quantity": 100,
        "id": "",
        "to_link": 52289,
        "relation": "FS",
        "buffer": 0
    },
    {
        "gantt_data_id": 21358,
        "location_id": 336,
        "location_name": "Allcargo Building",
        "sub_loc_id": 1814,
        "sub_loc_name": "3rd Floor",
        "sub_location_id": 4209,
        "sub_sub_loc_name": "A Wing",
        "linking_activity_id": 52303,
        "activity_head": "Misc",
        "activity": "Ready Made Planters",
        "productivity": 14.3,
        "quantity": 100,
        "id": "",
        "to_link": 52289,
        "relation": "FS",
        "buffer": 0
    },
    {
        "gantt_data_id": 21359,
        "location_id": 336,
        "location_name": "Allcargo Building",
        "sub_loc_id": 1814,
        "sub_loc_name": "3rd Floor",
        "sub_location_id": 4209,
        "sub_sub_loc_name": "A Wing",
        "linking_activity_id": 52304,
        "activity_head": "VRF",
        "activity": "Supply",
        "productivity": 100,
        "quantity": 100,
        "id": "",
        "relation": "PS",
        "buffer": 30,
        "__EMPTY_2": "HVAC"
    },
    {
        "gantt_data_id": 21360,
        "location_id": 336,
        "location_name": "Allcargo Building",
        "sub_loc_id": 1814,
        "sub_loc_name": "3rd Floor",
        "sub_location_id": 4209,
        "sub_sub_loc_name": "A Wing",
        "linking_activity_id": 52305,
        "activity_head": "VRF",
        "activity": "Installation",
        "productivity": 10,
        "quantity": 100,
        "id": "",
        "to_link": 52304,
        "relation": "FS",
        "buffer": 10,
        "__EMPTY_2": "HVAC"
    },
    {
        "gantt_data_id": 21361,
        "location_id": 336,
        "location_name": "Allcargo Building",
        "sub_loc_id": 1814,
        "sub_loc_name": "3rd Floor",
        "sub_location_id": 4209,
        "sub_sub_loc_name": "A Wing",
        "linking_activity_id": 52313,
        "activity_head": "VRF",
        "activity": "Commissioning",
        "productivity": 16.7,
        "quantity": 100,
        "id": "",
        "to_link": 52305,
        "relation": "FS",
        "buffer": 0,
        "__EMPTY_2": "HVAC"
    },
    {
        "gantt_data_id": 21389,
        "location_id": 336,
        "location_name": "Allcargo Building",
        "sub_loc_id": 1814,
        "sub_loc_name": "3rd Floor",
        "sub_location_id": 4209,
        "sub_sub_loc_name": "A Wing",
        "linking_activity_id": 52278,
        "activity_head": "Panelling",
        "activity": "Wall",
        "productivity": 3.8,
        "quantity": 100,
        "id": "",
        "to_link": 52270,
        "relation": "FS",
        "buffer": -15
    },
    {
        "gantt_data_id": 21367,
        "location_id": 336,
        "location_name": "Allcargo Building",
        "sub_loc_id": 1814,
        "sub_loc_name": "3rd Floor",
        "sub_location_id": 4209,
        "sub_sub_loc_name": "A Wing",
        "linking_activity_id": 52256,
        "activity_head": "Door",
        "activity": "Lintel",
        "productivity": 10,
        "quantity": 100,
        "id": "",
        "to_link": 52254,
        "relation": "SS",
        "buffer": 0
    },
    {
        "gantt_data_id": 21368,
        "location_id": 336,
        "location_name": "Allcargo Building",
        "sub_loc_id": 1814,
        "sub_loc_name": "3rd Floor",
        "sub_location_id": 4209,
        "sub_sub_loc_name": "A Wing",
        "linking_activity_id": 52257,
        "activity_head": "Door",
        "activity": "Frame Single Slab",
        "productivity": 20,
        "quantity": 100,
        "id": "",
        "to_link": 52273,
        "relation": "FS",
        "buffer": 0
    },
    {
        "gantt_data_id": 21369,
        "location_id": 336,
        "location_name": "Allcargo Building",
        "sub_loc_id": 1814,
        "sub_loc_name": "3rd Floor",
        "sub_location_id": 4209,
        "sub_sub_loc_name": "A Wing",
        "linking_activity_id": 52258,
        "activity_head": "Door",
        "activity": "Frame Double Slab",
        "productivity": 20,
        "quantity": 100,
        "id": "",
        "to_link": 52273,
        "relation": "FS",
        "buffer": 0
    },
    {
        "gantt_data_id": 21370,
        "location_id": 336,
        "location_name": "Allcargo Building",
        "sub_loc_id": 1814,
        "sub_loc_name": "3rd Floor",
        "sub_location_id": 4209,
        "sub_sub_loc_name": "A Wing",
        "linking_activity_id": 52259,
        "activity_head": "Waterproofing",
        "activity": "Basecoat",
        "productivity": 14.3,
        "quantity": 100,
        "id": "",
        "to_link": 52255,
        "relation": "FS",
        "buffer": 0
    },
    {
        "gantt_data_id": 21371,
        "location_id": 336,
        "location_name": "Allcargo Building",
        "sub_loc_id": 1814,
        "sub_loc_name": "3rd Floor",
        "sub_location_id": 4209,
        "sub_sub_loc_name": "A Wing",
        "linking_activity_id": 52260,
        "activity_head": "Waterproofing",
        "activity": "Brickbat coba",
        "productivity": 14.3,
        "quantity": 100,
        "id": "",
        "to_link": 52255,
        "relation": "FS",
        "buffer": 0
    },
    {
        "gantt_data_id": 21372,
        "location_id": 336,
        "location_name": "Allcargo Building",
        "sub_loc_id": 1814,
        "sub_loc_name": "3rd Floor",
        "sub_location_id": 4209,
        "sub_sub_loc_name": "A Wing",
        "linking_activity_id": 52261,
        "activity_head": "Pantry",
        "activity": "Dado",
        "productivity": 20,
        "quantity": 100,
        "id": "",
        "to_link": 52267,
        "relation": "FS",
        "buffer": 0
    },
    {
        "gantt_data_id": 21373,
        "location_id": 336,
        "location_name": "Allcargo Building",
        "sub_loc_id": 1814,
        "sub_loc_name": "3rd Floor",
        "sub_location_id": 4209,
        "sub_sub_loc_name": "A Wing",
        "linking_activity_id": 52262,
        "activity_head": "Pantry",
        "activity": "Counter",
        "productivity": 100,
        "quantity": 100,
        "id": "",
        "to_link": 52267,
        "relation": "FS",
        "buffer": 0
    },
    {
        "gantt_data_id": 21374,
        "location_id": 336,
        "location_name": "Allcargo Building",
        "sub_loc_id": 1814,
        "sub_loc_name": "3rd Floor",
        "sub_location_id": 4209,
        "sub_sub_loc_name": "A Wing",
        "linking_activity_id": 52263,
        "activity_head": "Toilet",
        "activity": "Dado",
        "productivity": 20,
        "quantity": 100,
        "id": "",
        "to_link": 52267,
        "relation": "FS",
        "buffer": 0
    },
    {
        "gantt_data_id": 21375,
        "location_id": 336,
        "location_name": "Allcargo Building",
        "sub_loc_id": 1814,
        "sub_loc_name": "3rd Floor",
        "sub_location_id": 4209,
        "sub_sub_loc_name": "A Wing",
        "linking_activity_id": 52264,
        "activity_head": "Toilet",
        "activity": "Counter",
        "productivity": 20,
        "quantity": 100,
        "id": "",
        "to_link": 52267,
        "relation": "FS",
        "buffer": 0
    },
    {
        "gantt_data_id": 21362,
        "location_id": 336,
        "location_name": "Allcargo Building",
        "sub_loc_id": 1814,
        "sub_loc_name": "3rd Floor",
        "sub_location_id": 4209,
        "sub_sub_loc_name": "A Wing",
        "linking_activity_id": 52265,
        "activity_head": "Toilet",
        "activity": "Urinal Partiton",
        "productivity": 50,
        "quantity": 100,
        "id": "",
        "relation": "PS",
        "buffer": 60
    },
    {
        "gantt_data_id": 21377,
        "location_id": 336,
        "location_name": "Allcargo Building",
        "sub_loc_id": 1814,
        "sub_loc_name": "3rd Floor",
        "sub_location_id": 4209,
        "sub_sub_loc_name": "A Wing",
        "linking_activity_id": 52266,
        "activity_head": "Floor",
        "activity": "PCC",
        "productivity": 20,
        "quantity": 100,
        "id": "",
        "to_link": 52255,
        "relation": "FS",
        "buffer": 0
    },
    {
        "gantt_data_id": 21378,
        "location_id": 336,
        "location_name": "Allcargo Building",
        "sub_loc_id": 1814,
        "sub_loc_name": "3rd Floor",
        "sub_location_id": 4209,
        "sub_sub_loc_name": "A Wing",
        "linking_activity_id": 52267,
        "activity_head": "Floor",
        "activity": "Common Area Tiles",
        "productivity": 14.3,
        "quantity": 100,
        "id": "",
        "to_link": 52266,
        "relation": "FS",
        "buffer": 0
    },
    {
        "gantt_data_id": 21379,
        "location_id": 336,
        "location_name": "Allcargo Building",
        "sub_loc_id": 1814,
        "sub_loc_name": "3rd Floor",
        "sub_location_id": 4209,
        "sub_sub_loc_name": "A Wing",
        "linking_activity_id": 52268,
        "activity_head": "Floor",
        "activity": "Toilet Tiles",
        "productivity": 14.3,
        "quantity": 100,
        "id": "",
        "to_link": 52266,
        "relation": "FS",
        "buffer": 0
    },
    {
        "gantt_data_id": 21380,
        "location_id": 336,
        "location_name": "Allcargo Building",
        "sub_loc_id": 1814,
        "sub_loc_name": "3rd Floor",
        "sub_location_id": 4209,
        "sub_sub_loc_name": "A Wing",
        "linking_activity_id": 52269,
        "activity_head": "Floor",
        "activity": "Skirting",
        "productivity": 14.3,
        "quantity": 100,
        "id": "",
        "to_link": 52266,
        "relation": "FS",
        "buffer": 0
    },
    {
        "gantt_data_id": 21381,
        "location_id": 336,
        "location_name": "Allcargo Building",
        "sub_loc_id": 1814,
        "sub_loc_name": "3rd Floor",
        "sub_location_id": 4209,
        "sub_sub_loc_name": "A Wing",
        "linking_activity_id": 52270,
        "activity_head": "Floor",
        "activity": "Vinyl",
        "productivity": 14.3,
        "quantity": 100,
        "id": "",
        "to_link": 52266,
        "relation": "FS",
        "buffer": 0
    },
    {
        "gantt_data_id": 21382,
        "location_id": 336,
        "location_name": "Allcargo Building",
        "sub_loc_id": 1814,
        "sub_loc_name": "3rd Floor",
        "sub_location_id": 4209,
        "sub_sub_loc_name": "A Wing",
        "linking_activity_id": 52271,
        "activity_head": "Masonary Wall",
        "activity": "POP Punning",
        "productivity": 14.3,
        "quantity": 100,
        "id": "",
        "to_link": 52255,
        "relation": "FS",
        "buffer": 0
    },
    {
        "gantt_data_id": 21383,
        "location_id": 336,
        "location_name": "Allcargo Building",
        "sub_loc_id": 1814,
        "sub_loc_name": "3rd Floor",
        "sub_location_id": 4209,
        "sub_sub_loc_name": "A Wing",
        "linking_activity_id": 52272,
        "activity_head": "False",
        "activity": "Ceiling",
        "productivity": 14.3,
        "quantity": 100,
        "id": "",
        "to_link": 52271,
        "relation": "FS",
        "buffer": 10
    },
    {
        "gantt_data_id": 21384,
        "location_id": 336,
        "location_name": "Allcargo Building",
        "sub_loc_id": 1814,
        "sub_loc_name": "3rd Floor",
        "sub_location_id": 4209,
        "sub_sub_loc_name": "A Wing",
        "linking_activity_id": 52273,
        "activity_head": "Partition",
        "activity": "Solid 2 side",
        "productivity": 3.8,
        "quantity": 100,
        "id": "",
        "to_link": 52270,
        "relation": "FS",
        "buffer": -15
    },
    {
        "gantt_data_id": 21385,
        "location_id": 336,
        "location_name": "Allcargo Building",
        "sub_loc_id": 1814,
        "sub_loc_name": "3rd Floor",
        "sub_location_id": 4209,
        "sub_sub_loc_name": "A Wing",
        "linking_activity_id": 52274,
        "activity_head": "Partition",
        "activity": "Solid 75 mm",
        "productivity": 3.8,
        "quantity": 100,
        "id": "",
        "to_link": 52270,
        "relation": "FS",
        "buffer": -15
    },
    {
        "gantt_data_id": 21386,
        "location_id": 336,
        "location_name": "Allcargo Building",
        "sub_loc_id": 1814,
        "sub_loc_name": "3rd Floor",
        "sub_location_id": 4209,
        "sub_sub_loc_name": "A Wing",
        "linking_activity_id": 52275,
        "activity_head": "Partition",
        "activity": "Solid 100 mm",
        "productivity": 3.8,
        "quantity": 100,
        "id": "",
        "to_link": 52270,
        "relation": "FS",
        "buffer": -15
    },
    {
        "gantt_data_id": 21387,
        "location_id": 336,
        "location_name": "Allcargo Building",
        "sub_loc_id": 1814,
        "sub_loc_name": "3rd Floor",
        "sub_location_id": 4209,
        "sub_sub_loc_name": "A Wing",
        "linking_activity_id": 52276,
        "activity_head": "Partition",
        "activity": "Glass 12mm",
        "productivity": 3.8,
        "quantity": 100,
        "id": "",
        "to_link": 52270,
        "relation": "FS",
        "buffer": -15
    },
    {
        "gantt_data_id": 21388,
        "location_id": 336,
        "location_name": "Allcargo Building",
        "sub_loc_id": 1814,
        "sub_loc_name": "3rd Floor",
        "sub_location_id": 4209,
        "sub_sub_loc_name": "A Wing",
        "linking_activity_id": 52277,
        "activity_head": "Toilet",
        "activity": "Mirror",
        "productivity": 3.8,
        "quantity": 100,
        "id": "",
        "to_link": 52270,
        "relation": "FS",
        "buffer": -15
    },
    {
        "gantt_data_id": 21376,
        "location_id": 336,
        "location_name": "Allcargo Building",
        "sub_loc_id": 1814,
        "sub_loc_name": "3rd Floor",
        "sub_location_id": 4209,
        "sub_sub_loc_name": "A Wing",
        "linking_activity_id": 52251,
        "activity_head": "Dismantling & Removing",
        "activity": "Tiles",
        "productivity": 7.7,
        "quantity": 100,
        "id": "",
        "relation": "PS",
        "buffer": 0
    },
    {
        "gantt_data_id": 21364,
        "location_id": 336,
        "location_name": "Allcargo Building",
        "sub_loc_id": 1814,
        "sub_loc_name": "3rd Floor",
        "sub_location_id": 4209,
        "sub_sub_loc_name": "A Wing",
        "linking_activity_id": 52253,
        "activity_head": "Dismantling & Removing",
        "activity": "Debris",
        "productivity": 33.3,
        "quantity": 100,
        "id": "",
        "to_link": 52251,
        "relation": "FS",
        "buffer": 0
    },
    {
        "gantt_data_id": 21363,
        "location_id": 336,
        "location_name": "Allcargo Building",
        "sub_loc_id": 1814,
        "sub_loc_name": "3rd Floor",
        "sub_location_id": 4209,
        "sub_sub_loc_name": "A Wing",
        "linking_activity_id": 52252,
        "activity_head": "Dismantling & Removing",
        "activity": "Vinyl",
        "productivity": 50,
        "quantity": 100,
        "id": "",
        "to_link": 52251,
        "relation": "FS",
        "buffer": 0
    },
    {
        "gantt_data_id": 21365,
        "location_id": 336,
        "location_name": "Allcargo Building",
        "sub_loc_id": 1814,
        "sub_loc_name": "3rd Floor",
        "sub_location_id": 4209,
        "sub_sub_loc_name": "A Wing",
        "linking_activity_id": 52254,
        "activity_head": "Masonary Wall",
        "activity": "Blockwork",
        "productivity": 10,
        "quantity": 100,
        "id": "",
        "to_link": 52253,
        "relation": "FS",
        "buffer": 0
    },
    {
        "gantt_data_id": 21366,
        "location_id": 336,
        "location_name": "Allcargo Building",
        "sub_loc_id": 1814,
        "sub_loc_name": "3rd Floor",
        "sub_location_id": 4209,
        "sub_sub_loc_name": "A Wing",
        "linking_activity_id": 52255,
        "activity_head": "Masonary Wall",
        "activity": "Plaster",
        "productivity": 20,
        "quantity": 100,
        "id": "",
        "to_link": 52254,
        "relation": "FS",
        "buffer": 0
    }
]


// console.log("arraaaaaaaaaaa",arr);

let dataStorage = []
let ganttSaveFile = []
let dataHere = arr
let obj = {}
let data1 = []


for (let i = 0; i < arr.length; i++) {
    if (arr[i].to_link && arr[i].planned_start_date == undefined) {
        dataStorage = []
        dataStorage.push(arr[i])
        findAndCalulateDateExcelUpload(arr[i].to_link)
    } else {
        if (arr[i].relation == "PS") {
            let paresntNumberOfDays = calculateDays(arr[i]) + arr[i].buffer
            arr[i]["planned_start_date"] = "2023-05-01"
            arr[i]["planned_end_date"] = moment(new Date(arr[i].planned_start_date)).add(parseInt(paresntNumberOfDays), 'days').format("YYYY-MM-DD")
        }
    }



}


function findAndCalulateDateExcelUpload(to_link) {

    let foundDataObj = arr.find(val => val.linking_activity_id == to_link)
    dataStorage.push(foundDataObj)
    let isTrue = false;
    if (foundDataObj.to_link) {
        isTrue = true;
        findAndCalulateDateExcelUpload(foundDataObj.to_link)
    } else {
        val = false;
    }

    if (isTrue) { return };

    let data = dataStorage.pop()
    let newArr = dataStorage.reverse()


    console.log("data is sssssssssssss", data);


    let paresntNumberOfDays = calculateDays(data)

    if(data.relation == "PS"){
        data["planned_start_date"] = "2023-05-01"
        data["planned_end_date"] = moment(new Date(data.planned_start_date)).add(parseInt(paresntNumberOfDays), 'days').format("YYYY-MM-DD")
    }
    


    for (let i = 0; i < newArr.length; i++) {
        let mainData = newArr[i]
        let numOfDays = calculateDays(mainData)

        // let TotalWorkingHrs = 0;
        // let finalQuantity = mainData.total_quantity ? mainData.total_quantity : mainData.quantity
        // TotalWorkingHrs = (((finalQuantity * 8) / mainData.productivity))
        // let daysAre = (TotalWorkingHrs / 8).toFixed()


        if (mainData.relation == "FS") {
            mainData["planned_start_date"] = moment(new Date(data.planned_end_date)).add(mainData.buffer, 'days').format("YYYY-MM-DD")
            mainData["planned_end_date"] = moment(new Date(mainData.planned_start_date)).add(parseInt(numOfDays), 'days').format("YYYY-MM-DD")
        }

        if (mainData.relation == "SS") {
            mainData["planned_start_date"] = moment(new Date(data.planned_start_date)).add(mainData.buffer, 'days').format("YYYY-MM-DD")
            mainData["planned_end_date"] = moment(new Date(mainData.planned_start_date)).add(parseInt(numOfDays), 'days').format("YYYY-MM-DD")
        }

        if (mainData.relation == "SF") {
            mainData["planned_end_date"] = moment(new Date(data.planned_start_date)).add(mainData.buffer, 'days').format("YYYY-MM-DD")
            mainData["planned_start_date"] = moment(new Date(mainData.planned_end_date)).subtract(parseInt(numOfDays), 'days').format("YYYY-MM-DD")
        }

        if (mainData.relation == "FF") {
            mainData["planned_end_date"] = moment(new Date(data.planned_end_date)).add(mainData.buffer, 'days').format("YYYY-MM-DD")
            mainData["planned_start_date"] = moment(new Date(mainData.planned_end_date)).subtract(parseInt(numOfDays), 'days').format("YYYY-MM-DD")
        }
        data = mainData
    }
    dataStorage = []
}


function calculateDays(mainData) {
    let TotalWorkingHrs = 0;
    let finalQuantity = mainData.total_quantity ? mainData.total_quantity : mainData.quantity
    TotalWorkingHrs = (((finalQuantity * 8) / mainData.productivity))
    let daysAre = (TotalWorkingHrs / 8).toFixed()
    return daysAre
}

console.log(JSON.stringify(arr));